sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t rafaelsanzio/tdd-multi-currencies -f Dockerfile.dev .

script:
  - docker run -e CI=true rafaelsanzio/tdd-multi-currencies npm run test
